# Telegram
api_id: 
api_hash: 
bot_token: 
shorten_url:
# if true use short.est that let you earn money on links, if false => goolnk
# Short.est Token
  shortest_token: 
# BitLy Token:
  bitly_token: 
# provider, choose between: [free, shortest, bitly]
  shorten_provider: 
# choose which shops to use
shops:
  amazon: true
  instant_gaming: false
  amazon_real: true
# amazon
amazon_affiliate: 
deals:
  min_discount: 
  max_price:
  filter_categories: true
  categories:
    other: false
    auto: false
    home: false
    # Smartphones, Headphones, Covers, TVs..
    electronics: false
    computer: false
    film: false
    toys: false
    lighting: false
    books: false
    music: false
    watches: false
    shoes: false
    sport: false
    videogames: false
# instant-gaming
instant_gaming_affiliate: 
# telegram 
telegram:
  channel_id: 
  repost_after_days: 
  posts_per_day: 
  # What hour of the day start to post [0-23]. Can be empty (it means it goes all the time)
  start_hour_of_day:  
  # What time stop to post. [0-23]. Cannot be set if start_hour is empty
  end_hour_of_day: 
  # Mutual Exclusive with end_hour_of_day.
  # If end_hour_of_day is provided -> It automatically calculate the delays between messages using posts_per_day
  # otherwise it will post every delay_message_minutes
  delay_message_minutes: 
  # Leave the | at start and be careful with indentation,
  message_template: |
        ⚡ You can use emoji
        And you can use the followings tags in your message: 
        {description}, {originalPrice}, {dealPrice}, {discount}, {url}, {hashtags}
        those will be automatically replaced.
        You can also use **BOLD**, or __Italic__ for formatting the text.
        leave an extra white line after the end of the message template
   
image_generator:
  image_template_uri: 
  font_uri: 
  # RGB like 255,255,255
  font_color:
  font_size: 
  # RGB like 0,0,0 => Can be blank, it means no border
  font_color_border:
